### PR TITLE
Hotfix: display curtain title after refreshing

### PR DESCRIPTION
**Pull request by codinfox**
暂时的方案是采用parse url的方法，更好的方案需要解决掉数据库的问题之后再研究。

### CODE REVIEW

**Comment by amio** [comment]
这个修正在页面刷新后会在控制台输出如下信息：

> React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

**Comment by codinfox** [comment]
嗯 看到了 研究一下 = =

**Comment by codinfox** [comment]
https://github.com/yahoo/flux-examples/issues/69

**Comment by amio** [comment]
事关 #9

**Pull request closed without merging**
